spring:
  datasource:
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    url: ${DB_URL:jdbc:postgresql://localhost:5432/local}
  jpa:
    hibernate:
      ddl-auto:  ${DB_JPA_DDL_AUTO:create-drop}
